services:
  backend-synkro:
    build: ./backend
    container_name: symfony_app
    restart: unless-stopped
    volumes:
      - ./backend:/var/www
    environment:
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres-synkro:${PORT_POSTGRES_2}/${POSTGRES_DB}?serverVersion=16&charset=utf8
    depends_on:
      - postgres-synkro
    ports:
      - ${PORT_BACKEND}
    networks:
      - synkronet-synkro

  websocket-synkro:
    build: ./server
    container_name: websocket_server
    restart: unless-stopped
    ports:
      - ${PORT_WEBSOCKET}
    volumes:
      - ./server:/app
    environment:
      - NODE_ENV=${NODE_ENV}
      - PORT=${PORT}
    networks:
      - synkronet-synkro

  postgres-synkro:
    image: postgres:16
    container_name: postgres_db
    restart: always
    ports:
      - ${PORT_POSTGRES}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - synkronet-synkro

volumes:
  postgres_data:

networks:
  synkronet-synkro:
    driver: bridge