services:
  backend-synkro:
    build: ./backend
    container_name: symfony_app
    restart: unless-stopped
    volumes:
      - ./backend:/var/www
    environment:
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
    depends_on:
      - postgres-synkro
    ports:
      - "8000:8000"
    networks:
      - synkronet-synkro

  frontend-synkro:
    build: ./frontend
    container_name: vue_frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    restart: unless-stopped
    networks:
      - synkronet-synkro

  websocket-synkro:
    build: ./server
    container_name: websocket_server
    restart: unless-stopped
    ports:
      - "3001:3001"
    volumes:
      - ./server:/app
    environment:
      - NODE_ENV=${NODE_ENV}
      - PORT=${PORT}
    networks:
      - synkronet-synkro

  postgres-synkro:
    image: postgres:16
    container_name: postgres_db
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - synkronet-synkro

volumes:
  postgres_data:

networks:
  synkronet-synkro:
    driver: bridge